# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(),
        ),
    ]
